### ISSUE TITLE
How to merge node tree?

### ISSUE THREAD

**Issue by fire** [wojtekpil/Godot-Octahedral-Impostors#10]
> Selecting a node tree with a GeometryInstance will also work.

I can't do this on your tree sample.

**Comment by fire** [comment]
>  res://addons/octahedral_impostors/octahedral_impostor_plugin.gd:52 - Invalid call. Nonexistent function 'set_scene_to_bake' in base 'WindowDialog (impostor_baker.gd)'

**Comment by wojtekpil** [comment]
For some reason it doesn't work good with root nodes, but something like this works fine for me:
![Screenshot from 2020-06-29 22-58-11](https://user-images.githubusercontent.com/1286923/86055491-25134980-ba5c-11ea-9177-5c0f87315c04.png)

As for the error, please enable plugin and try to reload your Godot project.

**Comment by fire** [comment]
I had to enable and disable the plugin. Then I got this. Will report back.

![image](https://user-images.githubusercontent.com/32321/86055827-3daa4200-ba11-11ea-83ac-34aee5b84f1b.png)

**Comment by fire** [comment]
Able to get a bake.
