### ISSUE TITLE
Suggest moving demo out of main repo

### ISSUE THREAD

**Issue by Arnklit** [wojtekpil/Godot-Octahedral-Impostors#18]
I just tried to install the add-on from the AssetLib. and it failed repeatedly half way through downloading. I guess most of the reason the Asset is big is because of the demo and that's also a bit unnecessary if you are already familiar with the asset and don't want the demo.

**Comment by wojtekpil** [comment]
I removed demo from project in v2.0-new-baker. It will replace master soon.
