### ISSUE TITLE
Rewrote to export to packed scene

### ISSUE THREAD

**Issue by fire** [wojtekpil/Godot-Octahedral-Impostors#4]
I rewrote some parts to be outputting a packed scene but the output being pixelated is stopping me.

Also there's a todo to export each png to a separate file and then linked to the packed scene.

[CameraOctahedral.txt](https://github.com/wojtekpil/Godot-Octahedral-Impostors/files/4794036/CameraOctahedral.txt)

You can use the same license you're using currently and you may wish to add my name to an authors list.

**Comment by fire** [comment]
FYI been using https://marketplace.visualstudio.com/items?itemName=Razoric.gdscript-toolkit-formatter

**Comment by wojtekpil** [comment]
Thanks for the input. I also have a plan on packing some textures to different channels of one image. It would decrease memory usage of GPU.

**Comment by fire** [comment]
Please use the orm texture format. It means occlusion, roughness and metalness.

**Comment by wojtekpil** [comment]
Added in 030cca97023362a1d6997786dced95876602e4c5

**Comment by wojtekpil** [comment]
The "packed scene" output files are huge. About 250 mb, where the images exported to PNG only take about 30 mb. I need to investigate this problem, because in its current form, those files are too big to store in the git.

**Comment by fire** [comment]
You need to save them as png to the filesystem and then link.

**Comment by fire** [comment]
Seem done.
