### ISSUE TITLE
Concept graph plugin 

### ISSUE THREAD

**Issue by fire** [wojtekpil/Godot-Octahedral-Impostors#5]
Polish enough so the parameters are easy to use and do not require tweaking to get a smooth result.

Possible to add to https://github.com/HungryProton/concept_graph

One of the steps is to convert the code to export to an meshinstance (Which I've done in another issue.)

**Comment by wojtekpil** [comment]
It would be nice to make it work with ConceptGraph. The need of manual setup of camera size is the biggest problem for that. I am still dissatisfied with this for now.

**Comment by fire** [comment]
You can use the "own world" check box to hide the camera and other things.

**Comment by wojtekpil** [comment]
Yes, but we need a  way to calculate orthographic camera size (and probably geometric centre of 3d object) for baking. For now, visual preview is necessary in baking process.

**Comment by fire** [comment]
A visual preview is not necessary after code updates. Any comments?

**Comment by wojtekpil** [comment]
Hi sorry, for the late reply. I don't think that integration with Concept Graph is a good idea right now. It moved to be a standalone tool, but my plugin is designed to work only inside Godot. It's useless without Godots specific shader language.

**Comment by fire** [comment]
As far as I know, one of the reasons the Concept Graph is stand alone is that Concept Graph uses my gltf2 export functionality. It's still using Godot Engine.

**Comment by wojtekpil** [comment]
Yes It's using Godot Engine, but it isn't a plugin now. I don't see a purpose to generate such impostors outside Godot. They won't work in any other 3d program. I think that my octahedral impostors are working far better as a standalone plugin. Of course I won't stop you if create a fork and integrate it in Concept Graph. For me at current state of Concept Graph it's kinda pointless.

**Comment by realkotob** [comment]
I also agree that since Concept Graph is becoming stand-alone it doesn't make much sense to port this to it.

The concept graph is best suited for content creation, whereas imposters are an optimization step for existing content, so it works best as a specialized uni-purpose plugin.

**Comment by fire** [comment]
Closing due to lack of support.
