### ISSUE TITLE
Demo scene is missing files

### ISSUE THREAD

**Issue by MrMinimal** [wojtekpil/Godot-Octahedral-Impostors#8]
Having a blast baking models already, what a great project!

When trying to open `res://demo/ForestTest.tscn` the following warning is displayed:
```
 Can't open file from path 'res://ImpostorShader.shader'.
 Failed to get modified time for: res://ImpostorShader.shader.
```
Also a minor nitpick would be that the demo's images are very big.
I had to switch to my desktop because my laptop crashed when importing them.

Can't wait to contribute to this!

Also: You have to add this to Godot's asset library!

**Comment by wojtekpil** [comment]
Demo files should be fixed. The images in the demos folder are 4k in size. Godot should not have a problem loading such files, but I can be wrong. If more people report a problem, I will change Textures to TextureArrays.
